.TH  multicheckpw 8 "qpasswd tools %VER%" "%DATE%" "System Administrator's Manual"
.SH NAME
\fBmulticheckpw\fR \- run multiple checkpasswords
.SH SYNOPSIS
\fBmulticheckpw\fR N checkprog1 checkprog2 ... checkprogN subprogram [\fBargs\fR]
.SH DESCRIPTION
Use this utility to check user,pass,greet pairs against multiple DjB
checkpassword-style programs. See http://cr.yp.to/checkpwd.html for
a description of how checkpassword works.
\fBmulticheckpw\fR assumes that when the child's exit code is 0,
then the password was accepted.
\fBmulticheckpw\fR takes n + 1 arguments, where n is the number of
checkpassword programs which should be called.
.SH PROCESS-STATE CHANGES
\fBmulticheckpw\fR doesn't make any process state changes, but the checkpassword
style programs it runs may change something ...
.SH RETURN VALUES
0\	password was okay
.br
1\	password failure
.br
2\	misuse
.br
111\	temporary failure
.SH SEE ALSO
.BR checkqpasswd (8),
.BR checkpasswd (8),
.BR cmd5checkpw (8),
.BR qpasswd (5)
.SH VERSION
This documentation describes \fBmulticheckpw\fR version %VER% of the qpasswd tools.
.SH AUTHOR
Tino Reichardt <milky-qpasswd@mcmilk.de>
