Document: qpasswd
Title: Debian qpasswd Manual
Author: <insert document author here>
Abstract: This manual describes what qpasswd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qpasswd/qpasswd.sgml.gz

Format: postscript
Files: /usr/share/doc/qpasswd/qpasswd.ps.gz

Format: text
Files: /usr/share/doc/qpasswd/qpasswd.text.gz

Format: HTML
Index: /usr/share/doc/qpasswd/html/index.html
Files: /usr/share/doc/qpasswd/html/*.html

  
